apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector: # expose app pods
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000 # Kubernetees Node Port
      targetPort: 4000 # container port where app is running
